name: Ruby Gem

on: push

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        git fetch --unshallow --tags
        echo $?
        # Check if the version already exists
        if git tag --list | grep $(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb); then echo "Version already exists!"; exit 1; fi
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # sets the git tag to the same version as the gem
    - run: |
        git config --local user.email "noreply@alchemic.it"
        git config --local user.name "AlchemicIT"
        git tag -a $(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb) -m "Version $(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb)"
        git push --tags
        
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}