name: Ruby Gem

on: push

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Check the version if it already exists as a tag, if so, exit, stop subsequent steps without failing the job
    - name: Check if tag exists
      run: |
        version=$(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb | awk -F'.' '{print $1"."$2"."$3}')
        if git rev-parse $version >/dev/null 2>&1
        then
          echo "Tag $version already exists, exiting"
          exit 0
        fi
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    # sets the git tag to the same version as the gem
    - run: |
        git config --local user.email "noreply@alchemic.it"
        git config --local user.name "AlchemicIT"
        version=$(grep -oP 'VERSION = "\K[^"]+' lib/*/version.rb | awk -F'.' '{print $1"."$2"."$3}')
        git tag -a $version -m "Version $version"
        git push --tags
        
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}